const vm=require('node:vm');
const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..');
const clone=v=>JSON.parse(JSON.stringify(v));
async function tick(){await new Promise(r=>setTimeout(r,30));}
(async()=>{
 const errors=[],v=new VirtualConsole();v.on('jsdomError',e=>errors.push(e));
 const dom=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{url:'http://127.0.0.1:8765/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:v});const w=dom.window;
 let phoneMock={paired:false,enabled:false,details:false,last:'',pair_code:''};
 let seatMock={term:'202601',crns:[],interval:120,observations:{},events:[],serial:0,running:false,reason:'',cycle_seconds:120,min_gap:10};
 let saved={term:'202601',courses:[],overrides:[],history:[],revision:0,solver_scope:'saved'};
 const realTimeout=w.setTimeout.bind(w);w.setTimeout=(fn,ms,...args)=>ms===2500?0:realTimeout(fn,ms,...args);
 let soundPulses=0,notifications=0;
 w.AudioContext=class {constructor(){this.state='running';this.currentTime=0;}async resume(){} createOscillator(){return {frequency:{setValueAtTime(){},linearRampToValueAtTime(){}},connect(){},start(){soundPulses++;},stop(){}};}createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime(){}},connect(){}};}};
 w.Notification=class{static permission='granted';static async requestPermission(){return 'granted';}constructor(){notifications++;}close(){}};
 w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 w.fetch=async(url,opts)=>{let data;if(url==='/api/plan')data=saved;else if(url==='/api/catalog')data=JSON.parse(fs.readFileSync(root+'/data/catalog.json'));else if(url==='/api/rules')data=JSON.parse(fs.readFileSync(root+'/data/spring-rules.json'));else if(url==='/api/seats')data=seatMock;else if(url==='/api/seats/config'){Object.assign(seatMock,JSON.parse(opts.body));data=seatMock;}else if(url==='/api/seats/start'){seatMock.running=true;data=seatMock;}else if(url==='/api/seats/stop'){seatMock.running=false;data=seatMock;}else if(url==='/api/draft'){const p=JSON.parse(opts.body),crns=p.courses.filter(r=>r.selected&&r.status!=='registered').flatMap(r=>r.crns.split(' '));data={ready:crns.length>0,crns,errors:[],warnings:[]};}else if(url==='/api/phone')data=phoneMock;else if(url==='/api/phone/connect'){phoneMock={...phoneMock,pair_code:'RS-test',configured:true};data=phoneMock;}else if(url==='/api/phone/pair'){phoneMock={...phoneMock,pair_code:'',paired:true};data=phoneMock;}else if(url==='/api/phone/config'){Object.assign(phoneMock,JSON.parse(opts.body));data=phoneMock;}else if(url==='/api/choice/review'){data={course:'CS303L',from:'10123',to:'12545',section:'A2',revision:saved.revision,warnings:[],crns:['12542','12545']};}else if(url==='/api/choice/apply'){saved.courses.forEach(r=>{if(r.course.replaceAll(' ','')==='CS303L')r.selected=r.crns==='12545';});saved.revision++;data=saved;}else if(url==='/api/crns/preview'||url==='/api/crns/import'){
 const input=JSON.parse(opts.body);
 const proc=require('node:child_process').spawnSync('python3',['-c',"import app,json,sys; from unittest.mock import patch; p=json.load(sys.stdin); ctx=patch.object(app,'read_plan',return_value=p['plan']); ctx.start(); print(json.dumps(app.review_import(p['payload'])))"],{cwd:root,input:JSON.stringify({plan:saved,payload:input}),encoding:'utf8'});
 if(proc.status!==0)return {ok:false,json:async()=>({error:'Import validation failed'})};
 const [next,preview]=JSON.parse(proc.stdout);
 if(url.endsWith('/preview'))data=preview;else{saved=next;saved.revision++;data=saved;}
 }else if(url==='/api/save'){saved=JSON.parse(opts.body);saved.revision++;data=saved;}else throw Error('Unexpected API '+url);return {ok:true,json:async()=>clone(data)};};
 for(const file of ['ui.js','catalog-ui.js','seats-ui.js','phone-ui.js'])vm.runInContext(fs.readFileSync(root+'/'+file,'utf8'),dom.getInternalVMContext());
 await tick();assert.equal(errors.length,0);assert(w.document.querySelectorAll('.catalog-course').length>400);
 const search=w.document.getElementById('catalog-search');search.value='CS303';search.dispatchEvent(new w.Event('input'));
 assert(w.document.querySelector('[data-crn="10119"]'));
 w.document.querySelector('[data-fallback="12542"]').click();await tick();assert.equal(saved.courses.length,1);assert.equal(saved.courses[0].selected,false);
 w.document.querySelector('[data-crn="10119"]').click();await tick();w.document.querySelector('[data-crn="10123"]').click();await tick();
 assert.deepEqual(saved.courses.filter(r=>r.selected).map(r=>r.crns),['10119','10123']);
 assert.equal(w.document.querySelectorAll('.tt-block').length,3);
 const blocks=[...w.document.querySelectorAll('.tt-block')];
 const short=blocks.find(b=>b.title.includes('09:40–10:30'));
 assert.equal(short.style.top,'84px');assert.equal(short.style.height,'70px');
 const long=blocks.find(b=>b.title.includes('12:40–14:30'));assert.equal(long.style.height,'154px');
 assert.equal(w.document.querySelector('.tt-cell').style.height,'70px');
 assert.equal(w.document.querySelectorAll('nav [data-view]').length,3);
 assert.equal(w.document.querySelector('.brand img').getAttribute('src'),'/assets/reticle.svg');
 assert.equal(w.document.querySelector('[data-crn="10119"]').disabled,false);
 w.document.querySelector('[data-crn="12542"]').click();await tick();
 assert.deepEqual(saved.courses.filter(r=>r.selected).map(r=>r.crns),['12542','10123']);
 // Lecture B and lab A1 are independently selectable despite different instructors.
 w.document.querySelector('[data-view="seats"]').click();w.document.getElementById('watch-plan').click();
 w.document.getElementById('monitor-start').click();await tick();
 assert(seatMock.running);assert.deepEqual(seatMock.crns,['12542','10123']);
 assert(w.document.getElementById('watch-crns').disabled);
 w.document.getElementById('sound-toggle').click();w.document.getElementById('desktop-toggle').click();await tick();
 assert.equal(soundPulses,3);assert.equal(notifications,0);
 vm.runInContext('audioCtx.currentTime=2',dom.getInternalVMContext());
 seatMock.observations['10123']={remaining:2,actual:198,capacity:200,checked_at:new Date().toISOString()};
 seatMock.events=[{id:1,term:'202601',crn:'10123',kind:'opened',remaining:2,at:new Date().toISOString()}];seatMock.serial=1;
 await vm.runInContext('pollSeats()',dom.getInternalVMContext());
 assert.equal(soundPulses,6);assert.equal(notifications,1);
 await vm.runInContext('pollSeats()',dom.getInternalVMContext());
 assert.equal(soundPulses,6);assert.equal(notifications,1);
 seatMock.observations['10123'].error='timeout';
 await vm.runInContext('pollSeats()',dom.getInternalVMContext());
 assert(w.document.getElementById('seat-rows').textContent.includes('Last observed: 2'));
 assert(!w.document.querySelector('.seat-number.available'));
 w.document.getElementById('monitor-start').click();await tick();assert(!seatMock.running);
 assert(!w.document.getElementById('watch-crns').disabled);
 w.document.querySelector('[data-view="plan"]').click();w.document.querySelector('[data-edit="1"]').click();
 const form=w.document.getElementById('course-form');assert(form.elements.namedItem('crns').readOnly);form.elements.namedItem('fallback_rank').value='2';form.elements.namedItem('locked').checked=true;form.dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(saved.courses[1].fallback_rank,2);assert.equal(saved.courses[1].locked,true);
 await new Promise(r=>setTimeout(r,180));
 assert(!w.document.getElementById('copy').disabled);assert(w.document.getElementById('prep-output').textContent.includes('12542'));
 assert(!w.document.getElementById('draft'));
 w.document.getElementById('phone-open').click();await tick();
 w.document.getElementById('phone-token').value='123456:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';w.document.getElementById('phone-connect').click();await tick();
 assert.equal(w.document.getElementById('phone-token').value,'');assert.equal(w.document.getElementById('phone-command').textContent,'/start RS-test');
 w.document.getElementById('phone-pair').click();await tick();assert(!w.document.getElementById('phone-enabled').disabled);
 w.document.getElementById('phone-enabled').checked=true;w.document.getElementById('phone-enabled').dispatchEvent(new w.Event('change'));await tick();assert(phoneMock.enabled);assert(!phoneMock.details);
 w.document.getElementById('phone-close').click();
 search.value='CS303';search.dispatchEvent(new w.Event('input'));w.document.querySelector('[data-fallback="12545"]').click();await tick();
 seatMock.opportunities=[{course:'CS303L',section:'A2',from:'10123',to:'12545'}];
 seatMock.combinations=[{course:'CS303',state:'available',components:[{course:'CS303',section:'B',state:'available'},{course:'CS303L',section:'A1',state:'available'}]}];
 await vm.runInContext('pollSeats()',dom.getInternalVMContext());assert(w.document.getElementById('combination-list').textContent.includes('Selected components have seats'));
 w.document.querySelector('#opportunity-list [data-choice]').click();await tick();assert(!w.document.getElementById('choice-apply').disabled);
 w.document.getElementById('choice-apply').click();await tick();assert(saved.courses.find(r=>r.crns==='12545').selected);assert(!saved.courses.find(r=>r.crns==='10123').selected);
 assert(!w.document.querySelector('#view-overrides'));
 // Import uses the real Python resolver with isolated in-memory state.
 saved={term:'202601',courses:[],overrides:[],history:[],revision:0,solver_scope:'saved'};
 vm.runInContext('plan='+JSON.stringify(saved)+';render();view("catalog")',dom.getInternalVMContext());
 w.document.getElementById('paste-crns').click();
 const paste=w.document.getElementById('crn-import-text');
 paste.value='10119\t10123\t13511\t10350\t10352\t10355\t12131\t10218\t10221\t10690\t10693';
 paste.dispatchEvent(new w.Event('input'));
 w.document.getElementById('crn-import-preview').click();await tick();
 assert.equal(saved.courses.length,0);
 assert.equal(w.document.querySelectorAll('#crn-import-result tbody tr').length,11);
 assert(w.document.getElementById('crn-import-result').textContent.includes('Preparation blocked'));
 assert(!w.document.getElementById('crn-import-apply').disabled);
 paste.dispatchEvent(new w.Event('input'));assert(w.document.getElementById('crn-import-apply').disabled);
 w.document.getElementById('crn-import-preview').click();await tick();
 w.document.getElementById('crn-import-apply').click();await tick();
 assert.equal(saved.courses.length,11);assert(saved.courses.every(r=>r.selected));
 const issues=w.document.getElementById('schedule-issues').textContent;
 assert(issues.includes('Tue 15:40–16:30'));assert(issues.includes('Fri 10:40–11:30'));
 assert(!w.document.getElementById('crn-import-dialog').open);
 const colored=[...w.document.querySelectorAll('.tt-block')];
 const courseColors=new Map();
 for(const b of colored){const color=b.style.getPropertyValue('--course-bg');assert(color);if(courseColors.has(b.dataset.course))assert.equal(color,courseColors.get(b.dataset.course));courseColors.set(b.dataset.course,color);}
 assert.equal(new Set(courseColors.values()).size,6);
 assert.equal(w.document.querySelectorAll('.tt-conflict').length,4);
 assert.equal(w.document.querySelectorAll('.tt-warning').length,4);
 const originalColors=[...courseColors];vm.runInContext('renderTimetable()',dom.getInternalVMContext());
 for(const [course,color] of originalColors)assert.equal(w.document.querySelector('.tt-block[data-course="'+course+'"]').style.getPropertyValue('--course-bg'),color);
 // A Thursday clash must not mark the same section's Tuesday meeting red.
 const econ=JSON.parse(fs.readFileSync(root+'/data/catalog.json')).courses.find(c=>c.code==='ECON 571');
 assert(econ.offerings.some(o=>o.crn==='13646'));
 vm.runInContext('plan.courses.push(catalogRow(catalogData.courses.find(c=>c.code==="ECON 571"),catalogData.courses.find(c=>c.code==="ECON 571").offerings.find(o=>o.crn==="13646")));renderTimetable()',dom.getInternalVMContext());
 const ee313=[...w.document.querySelectorAll('.tt-block[data-course="EE313"]')];
 const tuesday=ee313.find(b=>b.title.includes('Tue'));
 const thursday=ee313.find(b=>b.title.includes('Thu'));
 assert(tuesday);assert(thursday);assert(!tuesday.classList.contains('tt-conflict'));assert(!tuesday.querySelector('.tt-warning'));
 assert(thursday.classList.contains('tt-conflict'));assert(thursday.querySelector('.tt-warning'));
 assert(thursday.getAttribute('aria-label').includes('Time conflict'));
 assert(thursday.style.width.includes('50%'));
 w.document.getElementById('paste-crns').click();paste.value='99999';
 paste.dispatchEvent(new w.Event('input'));w.document.getElementById('crn-import-preview').click();await tick();
 assert(w.document.getElementById('crn-import-error').textContent);
 assert(w.document.getElementById('crn-import-apply').disabled);assert.equal(saved.courses.length,11);
 assert.equal(errors.length,0);dom.window.close();console.log('DOM UI integration: catalog search, backup save, lecture/lab selection, timetable blocks, section editing, aligned teaching cells, independent instructors, monitoring controls, sound/notification deduplication and unknown-seat states passed.');
 const mock=new JSDOM(fs.readFileSync(root+'/mock.html','utf8').replaceAll('__TERM__','202601'),{url:'http://127.0.0.1:8765/mock',runScripts:'outside-only'});const m=mock.window;
 m.HTMLElement.prototype.getClientRects=function(){return [{width:80,height:25}]};
 for(const file of ['mock.js','extension/autofill-core.js','extension/mock-adapter.js'])vm.runInContext(fs.readFileSync(root+'/'+file,'utf8'),mock.getInternalVMContext());
 const packet={ready:true,term:'202601',revision:1,crns:['99991','99992'],generated_at:new Date().toISOString()};
 let submits=0;m.document.querySelector('form').addEventListener('submit',()=>submits++);
 let preview=m.SniperMockAdapter.preview(packet);let result=await m.SniperMockAdapter.fill(packet,preview);
 assert.equal(result.verified,2);assert.equal(m.document.getElementById('crn-1').value,'99991');assert.equal(m.document.getElementById('unrelated').value,'Do not modify');assert.equal(submits,0);
 preview=m.SniperMockAdapter.preview(packet);result=await m.SniperMockAdapter.fill(packet,preview);assert.equal(result.filled,0);
 m.document.querySelector('form').reset();await tick();preview=m.SniperMockAdapter.preview(packet);
 m.document.getElementById('crn-2').addEventListener('change',()=>m.document.getElementById('crn-2').value='00000',{once:true});
 await assert.rejects(m.SniperMockAdapter.fill(packet,preview),/verification failed/);assert.equal(m.document.getElementById('crn-1').value,'');assert.equal(m.document.getElementById('crn-2').value,'');assert.equal(submits,0);
 mock.window.close();console.log('DOM adapter integration: actual value setters, independent fields, unrelated field untouched, no submit, repeat fill and rollback passed.');
})().catch(e=>{console.error(e);process.exit(1)});
