const text=s=>s.replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
export function parseSeats(html,term,crn){
 if(!/^\d{6}$/.test(term)||!/^\d{5}$/.test(crn))throw Error('Invalid course identity.');
 const links=[...html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)["']/gi)].map(m=>{try{return new URL(m[1].replaceAll('&amp;','&'),'https://suis.sabanciuniv.edu');}catch{return null;}});
 const identity=links.some(u=>u&&((u.searchParams.get('crn')===crn&&u.searchParams.get('term')===term)||(u.pathname==='/prod/bwckctlg.p_display_courses'&&u.searchParams.get('term_in')===term)));
 if(!identity||!text(html).includes(' - '+crn+' - '))throw Error('Course identity is missing or different.');
 const tables=[...html.matchAll(/<table\b[^>]*summary\s*=\s*["'][^"']*seating numbers[^"']*["'][^>]*>([\s\S]*?)<\/table>/gi)];if(tables.length!==1)throw Error('Seat table unavailable.');
 const rows=tables[0][1].split(/<tr\b[^>]*>/i).slice(1).map(row=>[...row.matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(m=>text(m[1])));
 if(!rows.some(r=>JSON.stringify(r)===JSON.stringify(['','Capacity','Actual','Remaining'])))throw Error('Seat column layout changed.');
 function totals(label,required=true){const found=rows.filter(r=>r[0]===label);if(!found.length&&!required)return null;if(found.length!==1||found[0].length!==4||found[0].slice(1).some(x=>!/^[-]?\d+$/.test(x)))throw Error('Invalid '+label+' totals.');const [capacity,actual,remaining]=found[0].slice(1).map(Number);if(![capacity,actual,remaining].every(Number.isSafeInteger)||capacity<0||actual<0||capacity-actual!==remaining)throw Error('Inconsistent seat counts.');return {capacity,actual,remaining};}
 const seats=totals('Seats'),cross_list=totals('Cross List Seats',false);return {...seats,cross_list,available:cross_list?Math.min(seats.remaining,cross_list.remaining):seats.remaining,source:`https://suis.sabanciuniv.edu/prod/bwckschd.p_disp_detail_sched?term_in=${term}&crn_in=${crn}`};
}
function jsonObject(s){let depth=0,quoted=false,escape=false;for(let i=0;i<s.length;i++){const c=s[i];if(quoted){if(escape)escape=false;else if(c==='\\')escape=true;else if(c==='"')quoted=false;}else if(c==='"')quoted=true;else if(c==='{')depth++;else if(c==='}'&&--depth===0)return JSON.parse(s.slice(0,i+1));}throw Error('Incomplete catalog data.');}
export function parseCatalog(html,term){const stream=[...html.matchAll(/self\.__next_f\.push\((\[1,.*?\])\)<\/script>/gs)].map(m=>JSON.parse(m[1])[1]).join('');if(!stream.includes('"id","'+term+'","d"'))throw Error('Catalog term could not be verified.');const at=stream.indexOf('"courses":');if(at<0)throw Error('Catalog data format changed.');const raw=jsonObject(stream.slice(at+10).trimStart()),ids=new Set(),days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
 const minutes=s=>{const m=String(s).match(/^(\d{1,2}):(\d{2}) (AM|PM)$/);return m&&+m[1]>=1&&+m[1]<=12&&+m[2]<60?(+m[1]%12+(m[3]==='PM'?12:0))*60+(+m[2]):null;};
 const courses=Object.entries(raw).map(([code,c])=>({code,name:c.name||code,offerings:c.offerings.map(o=>{if(!/^\d{5}$/.test(o.crn)||ids.has(o.crn))throw Error('Catalog contains invalid or duplicate CRNs.');ids.add(o.crn);let unknown=false;const meetings=(o.schedule||[]).map(m=>{const day=days.indexOf(m.day),start=minutes(m.start),end=minutes(m.end);if(day<0||start===null||end===null||end<=start){unknown=true;return null;}return {day,start,end,place:m.place||''};}).filter(Boolean);return {crn:o.crn,type:o.type||'',section:o.group||'',instructor:o.instructors||'',meetings,unknown_times:unknown||!meetings.length};})}));if(!courses.length)throw Error('Catalog is empty.');return {term,source:'https://sutable.vercel.app/'+term,fetched_at:new Date().toISOString(),courses,section_count:ids.size,pairing_rules_available:false};
}
export async function boundedHtml(url,max,fetcher=fetch){const r=await fetcher(url,{redirect:'manual',headers:{Accept:'text/html','User-Agent':'RegistrationSniper-Web/1.0 (public course availability)'},signal:AbortSignal.timeout(15000)});if([401,403,429].includes(r.status)||(r.status>=300&&r.status<400))throw Object.assign(Error('Public source blocked or redirected this request. Monitoring stopped.'),{blocked:true});if(!r.ok)throw Error('Public source returned HTTP '+r.status);if(!r.headers.get('content-type')?.includes('text/html'))throw Error('Unexpected public source response.');const reader=r.body.getReader(),parts=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw Error('Public response exceeded the size limit.');}parts.push(value);}const all=new Uint8Array(size);let p=0;for(const b of parts){all.set(b,p);p+=b.length;}const html=new TextDecoder().decode(all);if(/captcha|access denied|temporarily blocked/i.test(html))throw Object.assign(Error('Public source access challenge. Monitoring stopped.'),{blocked:true});return html;}
